[package]
name = "my_api"
version = "0.1.0"
authors = ["Dillon Dickerson <diltdicker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"